# Lab1: Tic-Tac-Toe

### Instructions:
- perform a fresh `restart & run all` before submitting
- [lab rubric](https://course.ccs.neu.edu/ds2500/admin_syllabus.html?highlight=rubric#weekly-lab-ds-2501)
- work in groups of 2-5
- be collaborative and kind
    - ask questions of others
    - invite questions from others
- each student will submit their own lab file
- please do not share code files 
    - however, unlike HW, you're welcome to look at each other's ungraded work

## Goal

Build a tic-tac-toe script which is capable of allowing two people to play tic tac toe by inputting their choices into the computer.  It may help to see example input / output in Part C to get a sense of how things will be put together before starting.


# Intro Video

- a few hints [here](https://northeastern.zoom.us/rec/share/DNvLITdjmGemDlDS2lvZgV4DsgT3o8X_MpEHQzobmlDc0T4BthTcpeTst-VoeKam._baKekYxA_qtO0LT) (~10 mins)


# You are given `get_position()`

Use the `get_position()` function below to get a user's desired position.


In [1]:
import numpy as np

def get_position(player_idx):
    """ gets a user's move via input().  no user input validation
    
    see also: get_apply_input()
    
    Args:
        player_idx (int): player idx (used to call 
            the player by name)

    Returns:
        row_idx (int): a row index
        col_idx (int): a col index
    """
    # get input from user
    pos = input(f'player{player_idx} input position: ')
    
    # parse user's input
    row_idx, col_idx = pos.split(',')
    row_idx = int(row_idx)
    col_idx = int(col_idx)
    
    return row_idx, col_idx


See usage of `get_position()` below:

- `>>>` indicates code cell lines you've run
    - (they don't show in jupyter, but this syntax indicates some place you'd put python code in general)
- The remaining lines are shown in output cells below.


```python
>>> get_position(player_idx=0)
```

```
player0 input position: 1, 0
    
Out[]: (1, 0)    
```


In [ ]:
# try it out yourself!
get_position(player_idx=0)


# Part A: `get_apply_input()`

Using the `get_position()` function above, complete the `get_apply_input()` function below.

#### Hints:
- Did we mention you should be using the given `get_position()`?
- Please assume that the user inputs a properly formatted position rather than some input which isn't proper
    - properly formatted inputs: `1, 1` or `0, 2`
    - improperly formatted inputs: `one, two`, `10, 0` or `-1, -1`

To validate that your `get_apply_input()` works, give it a few runs yourself.  Expected behavior is listed below. 

```python
>>> board = np.zeros((3, 3))
>>> get_apply_input(board, player_idx=1)
```

```
player1 input position: 0, 0
array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```
___________________________

```python
>>> board = np.zeros((3, 3))
>>> board[0, 0] = 1
>>> get_apply_input(board, player_idx=1)
```

```
player1 input position: 0, 0
invalid input given
player1 input position: 0, 1
array([[1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```




In [2]:
# build a board using arrays
board = np.zeros((3,3))

def get_apply_input(board, player_idx, board_null=0):
    """ gets input from user and applies their mark
    
    re-query if input given does not refer to a 
    position on the board currently marked as board_null
    
    Args:
        board (np.array): a 3x3 tic-tac-toe board
        player_idx (int): player whose turn is being taken
            (either 1 or 2)
        board_null (int): the value of open positions
            on the board
            
    Returns:
        board (np.array): a 3x3 tic-tac-toe board
            which has recorded 
    """     
    assert player_idx in (1, 2), 'invalid player_idx'
    
    # get the player's coordinate and split them into row and col
    row, col = get_position(player_idx)
    
    # inputting positions on board
    while True:
        # make sure that positions are plottable in 3x3 array
        if row in range(0,4) and col in range(0,4):
            # if board is empty, place the position
            if board[row, col] == board_null:
                board[row, col] = player_idx
                # stop if positions are valid
                break
        else:
            print("Invalid input. Please input coordinates within 0-3")
            
    
    # return a new board
    return board



In [ ]:
get_apply_input(board, player_idx=1, board_null=0)

# Part B: `get_win_set()`

Complete the `get_win_set()` function below.

One quirk of `get_win_set()` is that its possible some input `board` has multiple winners.  Consider:

```python
board = np.array([[0, 0, 0],
                  [1, 1, 1],
                  [2, 2, 2]])
```

absent any other information, it looks like there is three in a row of idx 0, 1 and 2.  `get_win_set()` should output the set `{0, 1, 2}`.

Some questions about this approach:
1. Isn't 0 reserved for `board_null` in `get_apply_input()` above?  How can 0 win?
2. This is kind of silly, this board couldn't have been created a in a real tic-tac-toe game, player 1 or 2 would have to win in some earlier turn before the other could also win

In part B, let's not bother with these kinds of details.  We can deal with it more simply in another part of our program.


In [3]:
def get_win_set(board):    
    """ returns a set of winning values in a board
    
    Args:
        board (np.array): a square tic-tac-toe board
        
    Returns:
        win_set (set): a set of items which fill an
            entire row, column, diagonal or off-diagonal
            (off-diagonal is top-right to bottom-left)
    """
    # create a win_set
    win_set = set()
    
    # make sure board shape aligns with the coordinate
    row_n, col_n = board.shape
    
    # check all rows
    for row_idx in range(row_n):
        row = board[row_idx, :]
        # if all rows have same design, add the design to win_set
        if all(row == row[0]):
            win_set.add(row[0])
            
            
    # check all col
    for col_idx in range(col_n):
        # if all cols have same design, add the design to win_set
        col = board[:, col_idx]
        if all(col == col[0]):
            win_set.add(col[0])
            
    # check the diagonal and add to win_set if same designs 
    diag = np.diag(board)
    if all(diag == diag[0]):
        win_set.add(diag[0])
        
    
    # check the left diagonal and add to win_set if same designs 
    off_diag = np.diag(np.rot90(board))
    if all(off_diag == off_diag[0]):
        win_set.add(off_diag[0])
    
    
    
    # return set
    return win_set
    
    


In [ ]:
get_win_set(board)

In [ ]:
assert get_win_set(board=np.zeros((3, 3))) == {0}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [2, 2, 2]])) == {0, 1, 2}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 2, 2],
                                   [1, 2, 2]])) == {1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 0, 0],
                                   [1, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 1, 0],
                                   [0, 1, 0],
                                   [0, 1, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 0, 1],
                                   [0, 0, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 1, 1],
                                   [0, 0, 0],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [0, 0, 0],
                                   [1, 1, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [0, 1, 0],
                                   [0, 0, 1]])) == {1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 1, 0],
                                   [1, 0, 0]])) == {1}


# Part C: Putting it all together in `play_tic_tac()`

Complete the function `play_tic_tac()` below which plays tic-tac-toe.  In addition to the example output shown below, the game should also stop if there are not any valid moves remaining.

#### Example input / output

```
[[0 0 0]
 [0 0 0]
 [0 0 0]]
player1 input position: 0, 0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
player2 input position: 0, 0
invalid input given
player2 input position: 0, 1
[[1 2 0]
 [0 0 0]
 [0 0 0]]
player1 input position: 1, 0
[[1 2 0]
 [1 0 0]
 [0 0 0]]
player2 input position: 0, 2
[[1 2 2]
 [1 0 0]
 [0 0 0]]
player1 input position: 2, 0
[[1 2 2]
 [1 0 0]
 [1 0 0]]
player 1 wins!
```


In [6]:
import numpy as np

def play_tic_tac(board_null=0, shape=(3, 3)):
    """ plays a game of tic-tac-toe on a 3x3 board
    
    Args:
        board_null (int): null value in board (spaces which
            player may select)
        shape (tuple): a tuple of length 2, num
            rows and num cols of tic-tac-toe board
    """
    # create loop for players
    for p_turn in range(10):
        player_choice = p_turn % 3
        
        # set the player_idx and print board after every turn
        if player_choice == 1:
            get_apply_input(board, player_idx = 1)
            print(board)
                
        elif player_choice == 2:
            get_apply_input(board, player_idx = 2)
            print(board)
        
        
        win = get_win_set(board)
        
        # remove the blank board if its in the win_set
        if board_null in win:
            win.remove(board_null)
        
        # the winner is the first player in the win set
        if len(win) == 1:
            print("Player", list(win)[0], "won!")
            break
        
        # if board is filled with no winner, it's a tie            
        if not (board == board_null).any():
            print("It is a tie!")
            break
    
    return board
        
        

In [7]:
# try it yourself!
play_tic_tac()


player1 input position: 0,0
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
player2 input position: 1,0
[[1. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
player1 input position: 0,1
[[1. 1. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]
player2 input position: 2,0
[[1. 1. 0.]
 [2. 0. 0.]
 [2. 0. 0.]]
player1 input position: 0,2
[[1. 1. 1.]
 [2. 0. 0.]
 [2. 0. 0.]]
Player 1.0 won!


array([[1., 1., 1.],
       [2., 0., 0.],
       [2., 0., 0.]])

# Part D (+.5 or +1): Add either one (but not both) extensions listed below


  
1. (+.5 pt) build a "random" opponent which selects an arbitrary, available location on the board
1. (+1 pt) build a "smart" opponent which plays according to some strategy of your choosing

If you attempt this extra credit, please add a markdown cell which clearly indicates which you've attempted.  For example:

```
    # We attempt Part D.1: building a "random" opponent
```

Note that part D requires you to modify your work above.  Please copy and paste any code you're modifying for part D below so that we can grade your work more easily.
