# Lab1: Tic-Tac-Toe

### Instructions:
- perform a fresh `restart & run all` before submitting
- [lab rubric](https://course.ccs.neu.edu/ds2500/admin_syllabus.html?highlight=rubric#weekly-lab-ds-2501)
- work in groups of 2-5
- be collaborative and kind
    - ask questions of others
    - invite questions from others
- each student will submit their own lab file
- please do not share code files 
    - however, unlike HW, you're welcome to look at each other's ungraded work

## Goal

Build a tic-tac-toe script which is capable of allowing two people to play tic tac toe by inputting their choices into the computer.  It may help to see example input / output in Part C to get a sense of how things will be put together before starting.


# Intro Video

- a few hints [here](https://northeastern.zoom.us/rec/share/DNvLITdjmGemDlDS2lvZgV4DsgT3o8X_MpEHQzobmlDc0T4BthTcpeTst-VoeKam._baKekYxA_qtO0LT) (~10 mins)


# You are given `get_position()`

Use the `get_position()` function below to get a user's desired position.


In [2]:
import numpy as np

def get_position(player_idx):
    """ gets a user's move via input().  no user input validation
    
    see also: get_apply_input()
    
    Args:
        player_idx (int): player idx (used to call 
            the player by name)

    Returns:
        row_idx (int): a row index
        col_idx (int): a col index
    """
    # get input from user
    pos = input(f'player{player_idx} input position: ')
    
    # parse user's input
    row_idx, col_idx = pos.split(',')
    row_idx = int(row_idx)
    col_idx = int(col_idx)
    
    return row_idx, col_idx


See usage of `get_position()` below:

- `>>>` indicates code cell lines you've run
    - (they don't show in jupyter, but this syntax indicates some place you'd put python code in general)
- The remaining lines are shown in output cells below.


```python
>>> get_position(player_idx=0)
```

```
player0 input position: 1, 0
    
Out[]: (1, 0)    
```


In [ ]:
# try it out yourself!
# get_position(player_idx=0)


# Part A: `get_apply_input()`

Using the `get_position()` function above, complete the `get_apply_input()` function below.

#### Hints:
- Did we mention you should be using the given `get_position()`?
- Please assume that the user inputs a properly formatted position rather than some input which isn't proper
    - properly formatted inputs: `1, 1` or `0, 2`
    - improperly formatted inputs: `one, two`, `10, 0` or `-1, -1`

To validate that your `get_apply_input()` works, give it a few runs yourself.  Expected behavior is listed below. 

```python
>>> board = np.zeros((3, 3))
>>> get_apply_input(board, player_idx=1)
```

```
player1 input position: 0, 0
array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```
___________________________

```python
>>> board = np.zeros((3, 3))
>>> board[0, 0] = 1
>>> get_apply_input(board, player_idx=1)
```

```
player1 input position: 0, 0
invalid input given
player1 input position: 0, 1
array([[1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```




In [ ]:
def get_apply_input(board, player_idx, board_null=0):
    """ gets input from user and applies their mark
    
    re-query if input given does not refer to a 
    position on the board currently marked as board_null
    
    Args:
        board (np.array): a 3x3 tic-tac-toe board
        player_idx (int): player whose turn is being taken
            (either 1 or 2)
        board_null (int): the value of open positions
            on the board
            
    Returns:
        board (np.array): a 3x3 tic-tac-toe board
            which has recorded 
    """    
    assert player_idx in (1, 2), 'invalid player_idx'
    
        while True:
        # get input from user
        row_idx, col_idx = get_position(player_idx)
        
        if board[row_idx, col_idx] == board_null:
            # user input valid: break
            break
            
        print('invalid input given')
        
    # apply user's input to board
    board[row_idx, col_idx] = player_idx
    
    return board   



# Part B: `get_win_set()`

Complete the `get_win_set()` function below.

One quirk of `get_win_set()` is that its possible some input `board` has multiple winners.  Consider:

```python
board = np.array([[0, 0, 0],
                  [1, 1, 1],
                  [2, 2, 2]])
```

absent any other information, it looks like there is three in a row of idx 0, 1 and 2.  `get_win_set()` should output the set `{0, 1, 2}`.

Some questions about this approach:
1. Isn't 0 reserved for `board_null` in `get_apply_input()` above?  How can 0 win?
2. This is kind of silly, this board couldn't have been created a in a real tic-tac-toe game, player 1 or 2 would have to win in some earlier turn before the other could also win

In part B, let's not bother with these kinds of details.  We can deal with it more simply in another part of our program.


In [1]:
def get_win_set(board):    
    """ returns a set of winning values in a board
    
    Args:
        board (np.array): a square tic-tac-toe board
        
    Returns:
        win_set (set): a set of items which fill an
            entire row, column, diagonal or off-diagonal
            (off-diagonal is top-right to bottom-left)
    """
    n_row, n_col = board.shape
    set_win = set()
    
    # row wins
    for row_idx in range(n_row):
        row = board[row_idx, :]
        if all(row == row[0]):
            set_win.add(row[0])
    
    # col wins
    for col_idx in range(n_col):
        col = board[:, col_idx]
        if all(col == col[0]):
            set_win.add(col[0])
    
    # diag wins
    diag0 = np.diag(board)
    if all(diag0 == diag0[0]):
        set_win.add(diag0[0])
    
    # off diag win
    diag1 = np.diag(np.rot90(board))
    if all(diag1 == diag1[0]):
        set_win.add(diag1[0])
        
    return set_win    



In [ ]:
assert get_win_set(board=np.zeros((3, 3))) == {0}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [2, 2, 2]])) == {0, 1, 2}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 2, 2],
                                   [1, 2, 2]])) == {1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [1, 0, 0],
                                   [1, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 1, 0],
                                   [0, 1, 0],
                                   [0, 1, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 0, 1],
                                   [0, 0, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 1, 1],
                                   [0, 0, 0],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [1, 1, 1],
                                   [0, 0, 0]])) == {0, 1}
assert get_win_set(board=np.array([[0, 0, 0],
                                   [0, 0, 0],
                                   [1, 1, 1]])) == {0, 1}
assert get_win_set(board=np.array([[1, 0, 0],
                                   [0, 1, 0],
                                   [0, 0, 1]])) == {1}
assert get_win_set(board=np.array([[0, 0, 1],
                                   [0, 1, 0],
                                   [1, 0, 0]])) == {1}


# (++) Fancy Part B: Local Functions and variable scope
There was some redundant code in our `get_win_set()`, wasn't there?  We can use an inner function to clarify things a bit.  The function `check_add_winner()` below is an "inner" function because it is defined inside `get_win_set_ex()`.  Note that `check_add_winner()` is only available within `get_win_set_ex()`.

Notice also that `set_win` is defined within `get_win_set_ex()`, yet it is used (and not passed as an input) to `check_add_winner()`.  If a variable is not available within some function, python leaves the function and searches if it exists there.  This construction allows the same `set_win` to be modified by consecutive calls to `check_add_winner()` without explicitly passing it.


In [ ]:
def get_win_set_ex(board):  
    """ returns a set of winning values in a board
    
    Args:
        board (np.array): a square tic-tac-toe board
        
    Returns:
        win_set (set): a set of items which fill an
            entire row, column, diagonal or off-diagonal
            (off-diagonal is top-right to bottom-left)
    """
    set_win = set()
    def check_add_winner(vec):
        # given input has all same value, add to win set
        if all(vec == vec[0]):
            set_win.add(vec[0])
    
    # row wins
    n_row, n_col = board.shape
    for row_idx in range(n_row):
        check_add_winner(board[row_idx, :])
        
    # col wins
    for col_idx in range(n_col):
        check_add_winner(board[:, col_idx])
    
    # diag & off-diag wins
    check_add_winner(np.diag(board))
    check_add_winner(np.diag(np.rot90(board)))
        
    return list_win    


# Part C: Putting it all together in `play_tic_tac()`

Complete the function `play_tic_tac()` below which plays tic-tac-toe.  In addition to the example output shown below, the game should also stop if there are not any valid moves remaining.

#### Example input / output

```
[[0 0 0]
 [0 0 0]
 [0 0 0]]
player1 input position: 0, 0
[[1 0 0]
 [0 0 0]
 [0 0 0]]
player2 input position: 0, 0
invalid input given
player2 input position: 0, 1
[[1 2 0]
 [0 0 0]
 [0 0 0]]
player1 input position: 1, 0
[[1 2 0]
 [1 0 0]
 [0 0 0]]
player2 input position: 0, 2
[[1 2 2]
 [1 0 0]
 [0 0 0]]
player1 input position: 2, 0
[[1 2 2]
 [1 0 0]
 [1 0 0]]
player 1 wins!
```


In [ ]:
import numpy as np

def play_tic_tac(board_null=0, shape=(3, 3)):
    """ plays a game of tic-tac-toe on a 3x3 board
    
    Args:
        board_null (int): null value in board (spaces which
            player may select)
        shape (tuple): a tuple of length 2, num
            rows and num cols of tic-tac-toe board
    """
    
        # initialize empty board
    board = np.full(shape=shape, 
                    fill_value=board_null)

    for round_idx in range(board.size + 1):
        print(board)
        
        # determine if any winners found
        win_set = get_win_set(board) - {0}
        if win_set:
            assert len(win_set) == 1, 'non-unique winner'
            
            # print winner message & stop game
            win_idx = list(win_set)[0]
            print(f'player{win_idx} wins!')
            break
            
        if not (board_null == board).any():
            # there are no more active moves remaining
            print('tie game')
            break

        # determine active player and get / apply their move
        player_active = (round_idx % 2) + 1
        board = get_apply_input(board=board, 
                                player_idx=player_active,
                                board_null=board_null)
    


In [ ]:
# try it yourself!
# play_tic_tac()


# Part D (+.5 or +1): Add either one (but not both) extensions listed below


  
1. (+.5 pt) build a "random" opponent which selects an arbitrary, available location on the board
1. (+1 pt) build a "smart" opponent which plays according to some strategy of your choosing

If you attempt this extra credit, please add a markdown cell which clearly indicates which you've attempted.  For example:

```
    # We attempt Part D.1: building a "random" opponent
```

Note that part D requires you to modify your work above.  Please copy and paste any code you're modifying for part D below so that we can grade your work more easily.


## Part D.1


In [ ]:
from random import randrange

def apply_input_rand(board, player_idx, board_null=0):
    """ applies random board move
    
    Args:
        board (np.array): a 3x3 tic-tac-toe board
        player_idx (int): player whose turn is being taken
            (either 1 or 2)
        board_null (int): the value of open positions
            on the board
            
    Returns:
        board (np.array): a 3x3 tic-tac-toe board
            which has recorded 
    """    
    assert player_idx in (1, 2), 'invalid player_idx'
    
    # ensure there is some valid position to choose
    assert (board == board_null).any(), 'no valid board positions'
    
    while True:
        # choose random board position
        row_idx = randrange(0, board.shape[0])
        col_idx = randrange(0, board.shape[1])
        
        if board[row_idx, col_idx] == board_null:
            # keep this position if its valid
            break
        
    print(f'computer player{player_idx} randomly chooses {row_idx}, {col_idx}')
        
    # mark board and return
    board[row_idx, col_idx] = player_idx
    
    return board   


In [ ]:
import numpy as np

def play_tic_tac_ex(player_input_fnc, board_null=0, shape=(3, 3)):
    """ plays a game of tic-tac-toe (flexible input fnc)
    
    Args:
        board_null (int): null value in board (spaces which
            player may select)
        shape (tuple): a tuple of length 2, num
            rows and num cols of tic-tac-toe board
        player_input_fnc (dict): keys are player index, values
            are function which applies input
    """
    # initialize empty board
    board = np.full(shape=shape, 
                    fill_value=board_null)

    for round_idx in range(board.size + 1):
        print(board)
        
        # determine if any winners found
        win_set = get_win_set(board) - {0}
        if win_set:
            assert len(win_set) == 1, 'non-unique winner'
            
            # print winner message & stop game
            win_idx = list(win_set)[0]
            print(f'player{win_idx} wins!')
            break
            
        if not (board_null == board).any():
            # there are no more active moves remaining
            print('tie game')
            break
        
        # get and apply move from active player
        player_active = (round_idx % 2) + 1
        fnc_apply = player_input_fnc[player_active]
        board = fnc_apply(board=board, 
                          player_idx=player_active,
                          board_null=board_null)


In [ ]:

# keys are player idx, values are functions which apply input
# (polymorphism preview: notice that we may use either function
# with the same inputs (board / player_idx, board_null) and they'll
# return the same outputs (board))
player_input_fnc = {1: get_apply_input,
                    2: apply_input_rand}

play_tic_tac_ex(player_input_fnc)
