# In Class Activity A

In a particular game a die is rolled such that:
- a player earns 10 points 1/2 of the time
- a player earns 20 points 1/3 of the time
- a player earns 30 points 1/6 of the time

Create a single call to `random.choices` which simulates 4 players being assigned points as above.  (Your output should be a list of 4 items)


In [1]:
# import choices from random
from random import choices

# choosing your population
population = ["10", "20", "30"]

# call choices with 4 random samples and its respective probability
choices(population, k = 4, weights = [1/2, 1/3, 1/6])




['10', '10', '20', '10']

In [2]:
# import random
import random

random.choices([10, 20, 30], weights=[1/2, 1/3, 1/6], k = 4)


[30, 20, 10, 10]

## In Class Activity B
1. Build an array by:
- getting 100 equally spaced values from 11 to 42
- reshaping it into an array with 5 columns
2. How much memory does the computer use to store the array above if ...
    - ... each item in array is a `float`
    - ... each item in array is an 8 bit unsigned integer `np.uint8`
        - is anything lost in this representation? (explain in comment please)
3. (++) Build an `11x11` checkerboard matrix.  A `3x3` checkerboard is shown below for reference:
$$ \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix} $$
- hint: try `[0, 1] * 3`, how could you use this?
- hint: you can slice matrices just like tuples / lists
    - `x[1:3]` gets the second and third items in an array


In [3]:
# import numpy
import numpy as np

# part 1
# use linspace: start w/ 11, stop at 42, size = 100
array = np.linspace(11, 42, 100)

# reshape to 5 columns; starting from their own choices
array.reshape((-1,5))

array([[11.        , 11.31313131, 11.62626263, 11.93939394, 12.25252525],
       [12.56565657, 12.87878788, 13.19191919, 13.50505051, 13.81818182],
       [14.13131313, 14.44444444, 14.75757576, 15.07070707, 15.38383838],
       [15.6969697 , 16.01010101, 16.32323232, 16.63636364, 16.94949495],
       [17.26262626, 17.57575758, 17.88888889, 18.2020202 , 18.51515152],
       [18.82828283, 19.14141414, 19.45454545, 19.76767677, 20.08080808],
       [20.39393939, 20.70707071, 21.02020202, 21.33333333, 21.64646465],
       [21.95959596, 22.27272727, 22.58585859, 22.8989899 , 23.21212121],
       [23.52525253, 23.83838384, 24.15151515, 24.46464646, 24.77777778],
       [25.09090909, 25.4040404 , 25.71717172, 26.03030303, 26.34343434],
       [26.65656566, 26.96969697, 27.28282828, 27.5959596 , 27.90909091],
       [28.22222222, 28.53535354, 28.84848485, 29.16161616, 29.47474747],
       [29.78787879, 30.1010101 , 30.41414141, 30.72727273, 31.04040404],
       [31.35353535, 31.66666667, 31.9

In [4]:
# part 2 - item is an float
array = np.linspace(11, 42, num = 100, dtype = float)
array.nbytes

800

In [5]:
# part 2 - array is an 8 bit unsigned integer
array = np.linspace(11, 42, num = 100, dtype = np.uint8)
array.nbytes

# all numbers in the array are now integers/whole numbers - not floats
# the array is randomly arrange - doesnt have a specific arrangement


100

## In Class Activity C

Using a single array slice, extract all values which match each value below in the matrix `x`
- 1
- 2
- 3
- 4
- 5

- extract the last column of x
- extract the last row of x
- extract the first three elements of the last column of x


In [6]:
x = np.array([[0., 1., 3., 0., 5., 5.],
              [0., 0., 3., 0., 0., 0.],
              [0., 2., 3., 0., 0., 0.],
              [0., 0., 3., 4., 4., 4.],
              [0., 0., 3., 4., 4., 4.],
              [0., 0., 3., 4., 4., 4.]])


In [7]:
# extract 1
x[0,1]

1.0

In [8]:
# extract 2
x[2,1]

2.0

In [9]:
# extract 3
x[:,2]

array([3., 3., 3., 3., 3., 3.])

In [10]:
# extract 4
x[3:,3:]

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [11]:
# extract 5
x[0,4:]

array([5., 5.])

In [12]:
# extract last column
x[:,-1]

array([5., 0., 0., 4., 4., 4.])

In [13]:
# extract the last row
x[-1,:]

array([0., 0., 3., 4., 4., 4.])

In [14]:
# extract first 3 element of last column
x[:3,-1]

array([5., 0., 0.])